version: '3.8'

services:
  # База данных MySQL для разработки
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: monastyr_db
      MYSQL_USER: monastyr_user
      MYSQL_PASSWORD: monastyr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monastyr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

volumes:
  mysql_dev_data:

networks:
  monastyr_network:
    driver: bridge
