-- AlterTable
ALTER TABLE `news`
ADD COLUMN `isVisible` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `User`
ADD COLUMN `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;